# Generated by Django 3.0.3 on 2021-03-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0023_check_staff_end_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_d',
            name='Course_Detail',
            field=models.CharField(blank=True, default='รายละเอียด', max_length=500, null=True),
        ),
    ]
