# Generated by Django 3.0.3 on 2021-03-16 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0025_auto_20210316_1117'),
    ]

    operations = [
        
        migrations.RenameField(
            model_name='course_d',
            old_name='End_Register',
            new_name='End_Time',
        ),
        migrations.RenameField(
            model_name='course_d',
            old_name='Open_Register',
            new_name='Start_Time',
        ),
        migrations.RemoveField(
            model_name='course_d',
            name='Course_Detail',
        ),
        
    ]
