# Generated by Django 3.0.3 on 2021-03-17 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0026_auto_20210316_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('Comp_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Comp_name', models.CharField(max_length=100, null=True)),
                ('Comp_type', models.CharField(max_length=2, null=True)),
                ('Comp_level', models.IntegerField(default=1, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='course_d',
            old_name='End_Time',
            new_name='End_Register',
        ),
        migrations.RenameField(
            model_name='course_d',
            old_name='Start_Time',
            new_name='Open_Register',
        ),
        migrations.AddField(
            model_name='course_d',
            name='Access_level',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('Subject_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Subject_name', models.CharField(max_length=150, null=True)),
                ('Description', models.TextField(default='เนื้อหาที่จะเรียน', null=True)),
                ('Url_location', models.CharField(blank=True, max_length=100)),
                ('Learding', models.TextField(default='ทักษะที่จะได้รับ', null=True)),
                ('Img_location', models.CharField(blank=True, max_length=100)),
                ('Class_duration', models.CharField(max_length=150, null=True)),
                ('ref_cou', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrence_course', to='register.Course_D')),
            ],
        ),
        migrations.CreateModel(
            name='Relation_subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mc_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ref_Mc', to='register.Competency')),
                ('Subject_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ref_sub', to='register.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Relation_comp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Course_relation', to='register.Course_D')),
                ('Subject_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Subject_relation', to='register.Subject')),
            ],
        ),
    ]
