# Generated by Django 3.0.3 on 2021-03-17 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0026_auto_20210316_1704'),
    ]

    operations = [
        
        migrations.RenameField(
            model_name='course_d',
            old_name='End_Time',
            new_name='End_Register',
        ),
        migrations.RenameField(
            model_name='course_d',
            old_name='Start_Time',
            new_name='Open_Register',
        )
    ]
