# Generated by Django 3.0.3 on 2021-03-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0027_auto_20210317_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_emp',
            name='Gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
