# Generated by Django 3.0.3 on 2021-03-17 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0027_auto_20210317_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='Subject',
            name='Learding',
            field= models.TextField(default='ทักษะที่จะได้รับ', null=True),
        ),
        migrations.AddField(
            model_name='Subject',
            name='Class_duration',
            field= models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='Subject',
            name='Img_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='Subject',
            name='Description',
            field=models.TextField(default='เนื้อหาที่จะเรียน', null=True),
        ),
    ]
