# Generated by Django 3.0.7 on 2021-03-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0028_list_emp_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Sub_level',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
